### ISSUE TITLE
Got an error when trying run **tools/set-developer-dir.sh**

### ISSUE THREAD

**Issue by warlockosx** [apple-cross-toolchain/rules_applecross#3]
Got an error when trying run **tools/set-developer-dir.sh**

$ tools/set-developer-dir.sh
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository apple_cross_toolchain instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule apple_cross_toolchain defined at:
  /home/vlad/.cache/bazel/_bazel_vlad/66038857d7a9ed64ac3643889e57b293/external/rules_applecross/toolchain/apple_cross_toolchain.bzl:259:40: in <toplevel>
ERROR: An error occurred during the fetch of repository 'apple_cross_toolchain':
   Traceback (most recent call last):
	File "/home/vlad/.cache/bazel/_bazel_vlad/66038857d7a9ed64ac3643889e57b293/external/rules_applecross/toolchain/apple_cross_toolchain.bzl", line 44
		resolve_labels(rctx, <1 more arguments>)
	File "/home/vlad/.cache/bazel/_bazel_vlad/66038857d7a9ed64ac3643889e57b293/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 38, in resolve_labels
		repository_ctx.path(<1 more arguments>)
Not a regular file: /home/vlad/.cache/bazel/_bazel_vlad/66038857d7a9ed64ac3643889e57b293/external/bazel_tools/tools/objc/libtool_check_unique.cc
ERROR: no such package '@apple_cross_toolchain//': Traceback (most recent call last):
	File "/home/vlad/.cache/bazel/_bazel_vlad/66038857d7a9ed64ac3643889e57b293/external/rules_applecross/toolchain/apple_cross_toolchain.bzl", line 44
		resolve_labels(rctx, <1 more arguments>)
	File "/home/vlad/.cache/bazel/_bazel_vlad/66038857d7a9ed64ac3643889e57b293/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 38, in resolve_labels
		repository_ctx.path(<1 more arguments>)
Not a regular file: /home/vlad/.cache/bazel/_bazel_vlad/66038857d7a9ed64ac3643889e57b293/external/bazel_tools/tools/objc/libtool_check_unique.cc
Loading: 0 packages loaded

**Comment by thii** [comment]
@warlockosx What versions of Bazel and rules_apple/rules_swift are you using?

**Comment by thii** [comment]
@warlockosx Sorry for not getting back earlier. This repo has changed a lot since then and no longer requires running anything to provision your machine.
